"""Add processing_time to AnalysisChunk

Revision ID: 1d3538b49415
Revises: 5895195404fc
Create Date: 2025-12-02 12:49:35.016661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3538b49415'
down_revision: Union[str, None] = '5895195404fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_chunks', sa.Column('processing_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_chunks', 'processing_time')
    # ### end Alembic commands ###
