"""Add task_ids to LabelingBatch

Revision ID: 3ebdee2a27a6
Revises: adfe1bd2b23a
Create Date: 2025-11-29 15:18:29.403142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ebdee2a27a6'
down_revision: Union[str, None] = 'adfe1bd2b23a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeling_batches', sa.Column('task_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeling_batches', 'task_ids')
    # ### end Alembic commands ###
