"""Add celery_task_id to training_runs

Revision ID: 84f872953674
Revises: f1604e7f039b
Create Date: 2025-11-30 08:09:33.827996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84f872953674'
down_revision: Union[str, None] = 'f1604e7f039b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_runs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_runs', 'celery_task_id')
    # ### end Alembic commands ###
