"""Add LabelingBatch and update LabelingProject

Revision ID: adfe1bd2b23a
Revises: 001_initial
Create Date: 2025-11-29 14:54:06.968398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfe1bd2b23a'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labeling_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('num_frames', sa.Integer(), nullable=True),
    sa.Column('frames_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['labeling_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('labeling_projects', sa.Column('video_id', sa.UUID(), nullable=True))
    op.add_column('labeling_projects', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('labeling_projects', sa.Column('export_path', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'labeling_projects', 'videos', ['video_id'], ['id'])
    op.drop_column('labeling_projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeling_projects', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'labeling_projects', type_='foreignkey')
    op.drop_column('labeling_projects', 'export_path')
    op.drop_column('labeling_projects', 'title')
    op.drop_column('labeling_projects', 'video_id')
    op.drop_table('labeling_batches')
    # ### end Alembic commands ###
