"""Add video_id to labeling_batches

Revision ID: afd3b83b746c
Revises: c6e49c1c63ff
Create Date: 2025-12-02 11:16:45.927994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afd3b83b746c'
down_revision: Union[str, None] = 'c6e49c1c63ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeling_batches', sa.Column('video_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'labeling_batches', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'labeling_batches', type_='foreignkey')
    op.drop_column('labeling_batches', 'video_id')
    # ### end Alembic commands ###
