"""Add current_step to calibrations

Revision ID: c6e49c1c63ff
Revises: 84f872953674
Create Date: 2025-11-30 13:16:19.691133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e49c1c63ff'
down_revision: Union[str, None] = '84f872953674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calibrations', sa.Column('current_step', sa.Integer(), nullable=True))
    op.add_column('calibrations', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calibrations', 'updated_at')
    op.drop_column('calibrations', 'current_step')
    # ### end Alembic commands ###
