"""Add view_id to LabelingBatch

Revision ID: f1604e7f039b
Revises: 3ebdee2a27a6
Create Date: 2025-11-29 15:39:00.344131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1604e7f039b'
down_revision: Union[str, None] = '3ebdee2a27a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('labeling_batches', sa.Column('view_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('labeling_batches', 'view_id')
    # ### end Alembic commands ###
